#!/usr/bin/env bash
# Naraya × Hermes Agent installer
# -------------------------------------------------------------------
# Installs Nous Research's Hermes agent on a fresh Ubuntu/Debian VPS,
# points its model provider at the Naraya router (OpenAI-compatible),
# wires up the Telegram gateway, and runs it as a systemd service.
#
# This file is the source of truth. It is mirrored to the PUBLIC repo
# github.com/naraya-ai/hermes-installer so the wizard one-liner can
# `curl` it unauthenticated. Pin releases with a git tag (e.g. v1).
#
# Usage (non-interactive, as generated by the wizard):
#   curl -fsSL https://raw.githubusercontent.com/naraya-ai/hermes-installer/v1/install.sh \
#     | sudo bash -s -- \
#       --key sk-nry-XXXX \
#       --base-url https://router.naraya.ai/v1 \
#       --model <default-alias> \
#       --models <alias1,alias2,...> \
#       --tg-token <bot-token> \
#       --tg-users <id1,id2>
#
# Run bare (no flags) on a TTY to be prompted interactively.
#
# Already have Hermes? Add --skip-install (alias --reconfigure) to only swap the
# model + API key and point it at the router. Telegram config is left untouched,
# so --tg-token / --tg-users are not needed:
#   curl -fsSL .../install.sh | sudo bash -s -- --skip-install \
#     --key sk-nry-XXXX --model <default-alias> --models <a,b,c>
#
# ASSUMPTIONS (verify against the Hermes version you target):
#   - `curl -fsSL https://hermes-agent.nousresearch.com/install.sh | bash`
#     installs the `hermes` CLI onto PATH for the running user.
#   - Hermes reads ~/.hermes/config.yaml + ~/.hermes/.env.
#   - `hermes gateway install --system` registers a systemd unit named
#     `hermes-gateway`. If the unit name differs, adjust SERVICE_NAME.
# -------------------------------------------------------------------
set -euo pipefail

# Do not leak secrets into the shell history of an interactive root shell.
set +o history 2>/dev/null || true

SERVICE_NAME="hermes-gateway"
BASE_URL="https://router.naraya.ai/v1"
PROVIDER_NAME="naraya"
KEY_ENV="NARAYA_API_KEY"

KEY=""
MODEL=""
MODELS=""
TG_TOKEN=""
TG_USERS=""
SKIP_INSTALL=""

log()  { printf '\033[1;36m¸ %s\033[0m\n' "$*"; }
ok()   { printf '\033[1;32m %s\033[0m\n' "$*"; }
warn() { printf '\033[1;33m! %s\033[0m\n' "$*" >&2; }
die()  { printf '\033[1;31m %s\033[0m\n' "$*" >&2; exit 1; }

# ---- args ----------------------------------------------------------
while [ $# -gt 0 ]; do
  case "$1" in
    --key)       KEY="${2:-}"; shift 2 ;;
    --base-url)  BASE_URL="${2:-}"; shift 2 ;;
    --model)     MODEL="${2:-}"; shift 2 ;;
    --models)    MODELS="${2:-}"; shift 2 ;;
    --tg-token)  TG_TOKEN="${2:-}"; shift 2 ;;
    --tg-users)  TG_USERS="${2:-}"; shift 2 ;;
    --skip-install|--reconfigure) SKIP_INSTALL=1; shift ;;
    -h|--help)
      grep -E '^#( |$)' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) die "Unknown argument: $1" ;;
  esac
done

# ---- interactive fallback ------------------------------------------
prompt() { # prompt VAR "label" [silent]
  local __var="$1" __label="$2" __silent="${3:-}" __val=""
  if [ -n "${!__var}" ]; then return; fi
  [ -t 0 ] || die "Missing --${__var//_/-} and no TTY to prompt."
  if [ "$__silent" = "silent" ]; then
    read -r -s -p "$__label: " __val; echo
  else
    read -r -p "$__label: " __val
  fi
  printf -v "$__var" '%s' "$__val"
}

prompt KEY      "Naraya API key (sk-nry-&)" silent
prompt MODEL    "Default model alias"
# Telegram is only set up on a fresh install. In --skip-install (reconfigure)
# mode we only swap the model/key and leave any existing Telegram config alone.
if [ -z "$SKIP_INSTALL" ]; then
  prompt TG_TOKEN "Telegram bot token"       silent
  prompt TG_USERS "Allowed Telegram user id(s), comma-separated"
fi

[ -n "$KEY" ]   || die "API key is required."
[ -n "$MODEL" ] || die "Default model is required."
if [ -z "$SKIP_INSTALL" ]; then
  [ -n "$TG_TOKEN" ] || die "Telegram bot token is required."
  [ -n "$TG_USERS" ] || die "At least one Telegram user id is required."
fi
case "$KEY" in sk-nry-*) ;; *) warn "API key does not start with sk-nry-  continuing anyway." ;; esac

# ---- privileges + platform -----------------------------------------
[ "$(id -u)" -eq 0 ] || die "Run as root (the systemd service install needs it). Re-run with sudo."

if command -v apt-get >/dev/null 2>&1; then
  PM="apt"
elif command -v pacman >/dev/null 2>&1; then
  PM="pacman"
else
  die "This installer supports Debian/Ubuntu (apt) and Arch Linux (pacman) only."
fi

# Install + configure Hermes under the invoking user, not root, when sudo was used.
TARGET_USER="${SUDO_USER:-root}"
TARGET_HOME="$(getent passwd "$TARGET_USER" | cut -d: -f6)"
[ -n "$TARGET_HOME" ] || die "Could not resolve home directory for $TARGET_USER."
HERMES_DIR="$TARGET_HOME/.hermes"

run_as() { # run a command as the target (non-root) user with their PATH
  if [ "$TARGET_USER" = "root" ]; then
    bash -lc "$1"
  else
    sudo -u "$TARGET_USER" -H bash -lc "$1"
  fi
}

# ---- dependencies + Hermes (skipped when reconfiguring) ------------
if [ -n "$SKIP_INSTALL" ]; then
  log "Reconfigure mode: skipping dependency + Hermes install."
  run_as 'command -v hermes >/dev/null 2>&1' \
    || die "Hermes is not installed for $TARGET_USER. Drop --skip-install to install it."
else
  log "Installing base dependencies (curl, git, python)&"
  if [ "$PM" = "apt" ]; then
    export DEBIAN_FRONTEND=noninteractive
    apt-get update -qq
    apt-get install -y -qq curl git ca-certificates python3 python3-venv python3-pip >/dev/null

    # Hermes needs Python >= 3.11. Ubuntu 22.04 ships 3.10 ’ pull deadsnakes.
    PYV="$(python3 -c 'import sys;print(sys.version_info[0]*100+sys.version_info[1])' 2>/dev/null || echo 0)"
    if [ "$PYV" -lt 311 ]; then
      warn "Python < 3.11 detected; adding deadsnakes for python3.11&"
      apt-get install -y -qq software-properties-common >/dev/null
      add-apt-repository -y ppa:deadsnakes/ppa >/dev/null 2>&1 || warn "Could not add deadsnakes PPA (Debian?). Hermes install may fail if Python < 3.11."
      apt-get update -qq
      apt-get install -y -qq python3.11 python3.11-venv >/dev/null 2>&1 || warn "python3.11 install failed; continuing."
    fi
  elif [ "$PM" = "pacman" ]; then
    pacman -Sy --noconfirm curl git ca-certificates python python-pip >/dev/null

    PYV="$(python3 -c 'import sys;print(sys.version_info[0]*100+sys.version_info[1])' 2>/dev/null || echo 0)"
    if [ "$PYV" -lt 311 ]; then
      warn "Python < 3.11 detected. Hermes install may fail if Python < 3.11."
    fi
  fi

  if run_as 'command -v hermes >/dev/null 2>&1'; then
    ok "Hermes already installed."
  else
    log "Installing Hermes agent (non-interactive)&"
    # --skip-setup + --non-interactive: never launch the provider wizard (we write
    # config.yaml + .env ourselves). --skip-browser: no Playwright on a headless
    # bot VPS. The upstream installer also auto-skips the wizard with no TTY.
    run_as 'curl -fsSL https://hermes-agent.nousresearch.com/install.sh | bash -s -- --skip-setup --non-interactive --skip-browser'
  fi
  run_as 'command -v hermes >/dev/null 2>&1' || die "Hermes CLI not on PATH after install. Open a new shell or check ~/.local/bin."
fi

# ---- write configuration ------------------------------------------
log "Writing configuration to $HERMES_DIR&"
install -d -m 700 -o "$TARGET_USER" "$HERMES_DIR"

# Quote the model defaults list for the human-readable reference comment.
MODELS_COMMENT="${MODELS:-$MODEL}"

cat > "$HERMES_DIR/config.yaml" <<YAML
# Managed by the Naraya × Hermes installer. Re-running the wizard overwrites this.
custom_providers:
  - name: ${PROVIDER_NAME}
    base_url: ${BASE_URL}
    key_env: ${KEY_ENV}

model:
  default: ${MODEL}
  provider: custom:${PROVIDER_NAME}

# Selected models (all reachable via /model custom:${PROVIDER_NAME}:<alias>):
#   ${MODELS_COMMENT}
YAML

# Secrets live only in .env. set_env upserts one KEY=VALUE, preserving any other
# lines  so reconfigure mode swaps the API key without wiping Telegram config.
ENV_FILE="$HERMES_DIR/.env"
umask 077
touch "$ENV_FILE"
set_env() { # set_env NAME VALUE
  local name="$1" value="$2" tmp
  tmp="$(mktemp)"
  grep -v -E "^${name}=" "$ENV_FILE" 2>/dev/null > "$tmp" || true
  printf '%s=%s\n' "$name" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
}

set_env "$KEY_ENV" "$KEY"
if [ -n "$TG_TOKEN" ]; then set_env "TELEGRAM_BOT_TOKEN" "$TG_TOKEN"; fi
if [ -n "$TG_USERS" ]; then set_env "TELEGRAM_ALLOWED_USERS" "$TG_USERS"; fi

chmod 600 "$ENV_FILE"
chown -R "$TARGET_USER":"$(id -gn "$TARGET_USER")" "$HERMES_DIR"
ok "Config written. Secrets in $ENV_FILE (chmod 600)."

# ---- (re)start service --------------------------------------------
if [ -n "$SKIP_INSTALL" ] && systemctl list-unit-files 2>/dev/null | grep -q "^${SERVICE_NAME}"; then
  log "Restarting the Hermes gateway service&"
  systemctl restart "$SERVICE_NAME" 2>/dev/null || run_as 'hermes gateway start' || warn "Could not restart $SERVICE_NAME."
else
  log "Installing the Hermes gateway systemd service&"
  # Hermes refuses --system as root unless --run-as-user is given (LXC/VPS root).
  GW_INSTALL="hermes gateway install --system"
  [ "$TARGET_USER" = "root" ] && GW_INSTALL="$GW_INSTALL --run-as-user root"
  # The installer prompts "start now?" / "enable on boot?"; our stdin is the curl
  # pipe (no TTY), so feed 'y' answers explicitly. printf (not `yes`) avoids a
  # SIGPIPE that pipefail would misread as failure.
  run_as "printf 'y\ny\ny\ny\n' | $GW_INSTALL" || warn "hermes gateway install --system returned non-zero; check Hermes version."
  systemctl daemon-reload 2>/dev/null || true
  systemctl enable --now "$SERVICE_NAME" 2>/dev/null || run_as 'hermes gateway start' || warn "Could not start via systemctl; started in foreground mode may be required."
fi

# ---- health check --------------------------------------------------
sleep 3
if systemctl is-active --quiet "$SERVICE_NAME" 2>/dev/null; then
  ok "Hermes gateway is active."
else
  warn "Service '$SERVICE_NAME' is not active yet. Check: journalctl -u $SERVICE_NAME -e"
fi

echo
ok "Done. Next steps:"
echo "  " Message your Telegram bot 'hi'  it should reply."
echo "  " Status: systemctl status $SERVICE_NAME"
echo "  " Logs:   journalctl -u $SERVICE_NAME -f"
echo "  " Switch model in chat: /model custom:${PROVIDER_NAME}:<alias>"
